/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.baitapnhom;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form(String name) {
        initComponents();
        setTitle(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldMaSv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldLop = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldGpa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangThongTinSinhVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sinh viên");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Lớp");

        jLabel4.setText("GPA");

        jButton1.setText("Hiển thị");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cập nhật");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        bangThongTinSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ tên", "Lớp", "GPA"
            }
        ));
        bangThongTinSinhVien.setToolTipText("");
        bangThongTinSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangThongTinSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangThongTinSinhVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2)
                        .addGap(55, 55, 55)
                        .addComponent(jButton3)
                        .addGap(61, 61, 61)
                        .addComponent(jButton4)
                        .addGap(60, 60, 60)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldLop, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fieldLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void hienThiDuLieu(){
        try{
            List<SinhVien> list = SinhVien.layDanhSachSinhVien();
            DefaultTableModel model = new DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                    "Mã sinh viên", "Họ tên", "Lớp", "GPA"
                }
            );
            for(SinhVien sinhVien:list){
                Object[] row= new Object[4];
                row[0] = sinhVien.getMaSv();
                row[1] = sinhVien.getHoTen();
                row[2] = sinhVien.getLop();
                row[3] = sinhVien.getGpa();
                model.addRow(row);
            }
            bangThongTinSinhVien.setModel(model);
        } catch(SQLException exception){
            exception.printStackTrace();
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi lấy dữ liệu.");
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO hien thi
        hienThiDuLieu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO them
        try{
            String maSv = fieldMaSv.getText();
            String hoTen = fieldHoTen.getText();
            String lop = fieldLop.getText();
            double gpa = Double.parseDouble(fieldGpa.getText());
            SinhVien sinhVien = new SinhVien(maSv, hoTen, lop, gpa);
            SinhVien.themSinhVien(sinhVien);
        } catch(SQLException exception){
            exception.printStackTrace();
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi thêm dữ liệu.");
        } catch(NumberFormatException exception){
            exception.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gpa phải là số thực.");
        }
        hienThiDuLieu();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO cap nhat
        try{
            String maSv = fieldMaSv.getText();
            String hoTen = fieldHoTen.getText();
            String lop = fieldLop.getText();
            double gpa = Double.parseDouble(fieldGpa.getText());
            SinhVien sinhVien = new SinhVien(maSv, hoTen, lop, gpa);
            SinhVien.suaSinhVien(sinhVien);
        } catch(SQLException exception){
            exception.printStackTrace();
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi sửa dữ liệu.");
        }
        hienThiDuLieu();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO xoa
        try{
            String maSv = fieldMaSv.getText();
            SinhVien.xoaSinhVien(maSv);
        } catch(SQLException exception){
            exception.printStackTrace();
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi xóa dữ liệu.");
        }
        hienThiDuLieu();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            SinhVien.reset();
            JOptionPane.showMessageDialog(null, "Xóa cơ sở dữ liệu thành công");
        } catch (SQLException exception) {
            exception.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi xóa cơ sở dữ liệu");
        }
        hienThiDuLieu();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bangThongTinSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangThongTinSinhVienMouseClicked
        // TODO add your handling code here:
        int row = bangThongTinSinhVien.getSelectedRow();
        if (row != -1) { // Kiểm tra xem có hàng nào được chọn không
            // Lấy thông tin từ hàng
            String maSv = (String) bangThongTinSinhVien.getValueAt(row, 0); 
            String hoTen = (String) bangThongTinSinhVien.getValueAt(row, 1); 
            String lop = (String) bangThongTinSinhVien.getValueAt(row, 2); 
            double gpa = (double) bangThongTinSinhVien.getValueAt(row, 3);
            fieldMaSv.setText(maSv);
            fieldHoTen.setText(hoTen);
            fieldLop.setText(lop);
            fieldGpa.setText(Double.toString(gpa));
        }
    }//GEN-LAST:event_bangThongTinSinhVienMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangThongTinSinhVien;
    private javax.swing.JTextField fieldGpa;
    private javax.swing.JTextField fieldHoTen;
    private javax.swing.JTextField fieldLop;
    private javax.swing.JTextField fieldMaSv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
